steps:
  - name: 'gcr.io/cloud-builders/mvn'
  args: ['package', 'appengine:stage', '-DskipTests']
  - name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'target/appengine-staging/app.yaml']