runtime: java11
instance_class: F2
service: ksft-opendr-user-service-uat
health_check:
  enable_health_check: False
env_variables:
  SERVICE_NAME: "ksft-opendr-user-service"
automatic_scaling:
  min_instances: 2
  max_instances: 15
  min_pending_latency: 3s
  max_concurrent_requests: 50
  min_idle_instances: 1